routes/web.php
<?php

use App\Http\Controllers\CandidateController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\VacancyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::fallback(function () {
    return view('error404');
});

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');

Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'register'])->name('register.create');

Route::middleware('auth')->group(function () {

    Route::get('/', function () {
        return view('home.index');
    })->name('home');

    Route::resource('vacancy', VacancyController::class);

    Route::prefix('vacancy')->group(function () {
        Route::post('{vacancy}/add-candidates', [VacancyController::class, 'addCandidates'])->name('vacancy.candidates.add');
        Route::put('{vacancy}/paused', [VacancyController::class, 'alterPaused'])->name('vacancy.paused');
        Route::delete('remove/candidates', [VacancyController::class, 'removeCandidates'])->name('vacancy.remove.candidates');
    });

    Route::resource('candidate', CandidateController::class);

    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
});

app/Models/Candidate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Candidate extends Model
{
    use HasFactory;

    protected $table = "candidates";

    protected $fillable = [
        "name",
        "email",
    ];

    public function vacancies()
    {
        return $this->hasMany(VacanciesCandidates::class, "candidates_id", "id");
    }
}

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use App\Models\Candidate;
use App\Models\VacanciesCandidates;
use Illuminate\Http\Request;

class CandidateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private Candidate $candidate;
    private VacanciesCandidates $vacanciesCandidates;

    function __construct(Candidate $candidate, VacanciesCandidates $vacanciesCandidates)
    {
        $this->candidate = $candidate;
        $this->vacanciesCandidates = $vacanciesCandidates;
    }

    public function index()
    {
        $order = request('order', 1);
        $orderBy = ($order == 1 || $order == 2) ? 'created_at' : 'updated_at';
        $sort = $order == 1 || $order == 3 ? 'DESC' : 'ASC';

        $perPage = request('per_page', 20);

        $candidates = $this->candidate::select('id', 'name', 'email', 'created_at')
            ->orderBy($orderBy, $sort)
            ->paginate($perPage);

        return view('candidate.index', [
            "candidates" => $candidates,
            "order" => $order,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('candidate.action');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->DataValidation($request);

        $data = request(['name', 'email']);

        $this->candidate->create($data);

        return redirect()->route('candidate.index')
            ->with('created', 'Candidato criado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $candidate = $this->candidate::find($id);

        if ($candidate) {

            $vacancies = $candidate->vacancies()
                ->select('vacancies_candidates.id as id', 'vacancies_candidates.created_at as created_at', 'vacancies.title as title', 'vacancies.description as description', 'vacancies.id as vacancy_id')
                ->join('vacancies', 'vacancies_candidates.vacancies_id', '=', 'vacancies.id')
                ->get();

            return view('candidate.show', [
                'candidate' => $candidate,
                'vacancies' => $vacancies,
            ]);
        }

        return view('error404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $candidate = $this->candidate::find($id);

        if ($candidate) {
            return view('candidate.action', [
                'candidate' => $candidate,
            ]);
        }

        return view('error404');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->DataValidation($request);

        $data = request(['name', 'email']);

        $candidate = $this->candidate::find($id);

        $candidate->update($data);
        $candidate->save();

        return redirect()->route('candidate.show', ['candidate' => $id])
            ->with('updated', 'Candidato atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $candidate = $this->candidate::find($id);
        $candidate->delete();

        return redirect()->route('candidate.index')
        ->with('destroyed', 'Candidato excluído com sucesso');
    }

    public function DataValidation($request)
    {
        return $this->validate($request, [
            'name' => 'required|string|min:4|max:50',
            'email' => 'required|email|max:150',
        ], [
            'required' => 'Esse campo é obrigatório',
            'max' => 'O número máximo de caracteres é :max',
            'min' => 'O número mínimo de caracteres é :min',
            'email' => 'Digite um e-mail válido',
        ]);
    }
}

resources/views/candidate/action.blade.php
@extends('layouts.template')

@section('title')
    @if (empty($candidate))
        Adicionando novo candidato
    @else
        Atualizando candidato
    @endif
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('assets/css/candidate/action.css')}}">
@endsection

@section('content')
    <div class="content">
        <a class="button-back mt-n2" href="@if(empty($candidate)) {{ route('candidate.index') }} @else {{ route('candidate.show', ['candidate' => $candidate->id]) }} @endif">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" height="30px" widht="30px" fill="#000000">
                <path
                    d="M447.1 256C447.1 273.7 433.7 288 416 288H109.3l105.4 105.4c12.5 12.5 12.5 32.75 0 45.25C208.4 444.9 200.2 448 192 448s-16.38-3.125-22.62-9.375l-160-160c-12.5-12.5-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25L109.3 224H416C433.7 224 447.1 238.3 447.1 256z" />
            </svg>
        </a>
        <h2 class="title">
            @if (empty($candidate))
                Adicionando novo candidato
            @else
                Atualizando candidato
            @endif
        </h2>

        <form action="@if(empty($candidate)) {{route('candidate.store')}} @else {{route('candidate.update', ['candidate' => $candidate->id])}} @endif" method="POST">
            @csrf
            @if (!empty($candidate))
                @method('PUT')
            @endif

            <div class="form-group">
                <label for="name">Nome do candidato</label>
                <input class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Digite o nome do candidato..." value="@if(empty($candidate)){{old('name')}}@else{{$candidate->name}}@endif" />
                <div class="invalid-feedback ml-2">
                    {{ $errors->first('name') }}
                </div>
            </div>

            <div class="form-group">
                <label for="email">E-mail do candidato</label>
                <input class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Digite o e-mail do candidato..." value="@if(empty($candidate)){{old('email')}}@else{{$candidate->email}}@endif" />
                <div class="invalid-feedback ml-2">
                    {{ $errors->first('email') }}
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="form-control btn btn-success">
                    @if(empty($candidate)) Adicionar @else Atualizar @endif
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/candidate/index.blade.php
@extends('layouts.template')

@section('title', 'Candidatos')

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/candidate/index.css') }}">
@endsection

@section('content')

    <div class="content">
        <div>
            <a class="button-back" href="{{ route('home') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" height="30px" widht="30px" fill="#000000">
                    <path
                        d="M447.1 256C447.1 273.7 433.7 288 416 288H109.3l105.4 105.4c12.5 12.5 12.5 32.75 0 45.25C208.4 444.9 200.2 448 192 448s-16.38-3.125-22.62-9.375l-160-160c-12.5-12.5-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25L109.3 224H416C433.7 224 447.1 238.3 447.1 256z" />
                </svg>
            </a>
            <h1 class="title-list mb-5">Lista de Candidatos</h1>
        </div>

        @if (session('created'))
            <div data-dismiss="alert" class="alert alert-success" role="alert">
                {{ session('created') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        @if (session('destroyed'))
            <div data-dismiss="alert" class="alert alert-danger" role="alert">
                {{ session('destroyed') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <main>
            <div class="d-flex justify-content-between">
                <a href="{{ route('candidate.create') }}" class="btn btn-success">
                    Adicionar novo candidato
                </a>

                <div class="d-flex">

                    <form action="{{ route('candidate.index') }}" class="form-inline" method="GET">
                        <div class="form-group">
                            <input type="hidden" value={{$candidates->perPage()}} name="per_page">
                            <label for="list_order">Ordenar por</label>
                            <select id="list_order" class="form-control ml-3 mr-4" name="order" onchange="this.form.submit()">
                                <option @if ($order == 1) selected @endif value="1">Recentemente criado
                                </option>
                                <option @if ($order == 2) selected @endif value="2">Mais antigos</option>
                                <option @if ($order == 3) selected @endif value="3">Atualizados recentemente
                                </option>
                                <option @if ($order == 4) selected @endif value="4">Mais desatualizado
                                </option>
                            </select>
                        </div>
                    </form>

                    <form action="{{ route('candidate.index') }}" class="form-inline" method="GET">
                        <div class="form-group">
                            <input type="hidden" value={{$order}} name="order">
                            <label for="list_order">resultados por página</label>
                            <select id="list_order" class="form-control ml-3" name="per_page" onchange="this.form.submit()">
                                <option @if($candidates->perPage() == 20) selected @endif >20</option>
                                <option @if($candidates->perPage() == 50) selected @endif >50</option>
                                <option @if($candidates->perPage() == 100) selected @endif >100</option>
                                <option @if($candidates->perPage() == 1000) selected @endif >1000</option>
                            </select>
                        </div>
                    </form>
                </div>
            </div>

            @foreach ($candidates as $candidate)
                <div class="mt-3">
                    <div class="card p-3">
                        <div class="d-flex justify-content-between">
                            <h5 class="card-title">
                                {{ $candidate->name }}
                            </h5>
                            <h6>{{ date_format($candidate->created_at, 'd M') }}</h6>
                        </div>

                        <div class="d-flex justify-content-between">
                            <p class="card-text">
                                {{ $candidate->email }}
                            </p>

                            <a href="{{ route('candidate.show', ['candidate' => $candidate->id]) }}"
                                class="btn btn-primary">
                                Ver mais
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach

            <div class="mt-4">
                {{ $candidates->withQueryString()->links() }}
            </div>
        </main>
    </div>

@endsection

resources/views/candidate/show.blade.php
@extends('layouts.template')

@section('title')
    {{ $candidate->name }}
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/candidate/show.css') }}">
@endsection

@section('content')
    <div class="content">
        <header>
            <a class="button-back" href="{{ route('candidate.index') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" height="30px" widht="30px" fill="#000000">
                    <path
                        d="M447.1 256C447.1 273.7 433.7 288 416 288H109.3l105.4 105.4c12.5 12.5 12.5 32.75 0 45.25C208.4 444.9 200.2 448 192 448s-16.38-3.125-22.62-9.375l-160-160c-12.5-12.5-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25L109.3 224H416C433.7 224 447.1 238.3 447.1 256z" />
                </svg>
            </a>
            <h2 class="title ml-5">
                {{ $candidate->name }}
            </h2>

            <div class="list-actions">

                <a href="{{ route('candidate.edit', ['candidate' => $candidate->id]) }}" class="btn btn-warning"
                    title="Editar">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF">
                        <path d="M0 0h24v24H0z" fill="none" />
                        <path
                            d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
                    </svg>
                </a>

                <form action="{{ route('candidate.destroy', ['candidate' => $candidate->id]) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger" title="Excluir">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                            fill="#FFFFFF">
                            <path d="M0 0h24v24H0z" fill="none" />
                            <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
                        </svg>
                    </button>
                </form>
            </div>
        </header>

        @if (session('updated'))
            <div data-dismiss="alert" class="alert alert-success mt-4" role="alert">
                {{ session('updated') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="d-flex flex-column mt-4">
            <span><b>E-mail: </b>{{ $candidate->email }}</span>
            <span><b>Criado em: </b>{{ date_format($candidate->created_at, 'd/m/y G:i') }}</span>
        </div>

        <section>
            <div class="d-flex justify-content-between mt-4">
                <h3>Vagas candidatadas</h3>

                @if ($vacancies->all())
                    <button type="submit" class="btn btn-danger" data-target="#removeCandidatesModal" data-toggle="modal">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                            fill="#FFFFFF">
                            <path d="M0 0h24v24H0z" fill="none" />
                            <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
                        </svg>
                    </button>
                @endif
            </div>

            @if (session('vaga removed'))
                <div data-dismiss="alert" class="alert alert-danger mt-4" role="alert">
                    {{ session('vaga removed') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            @if ($vacancies->all())
                <div class="row">
                    @foreach ($vacancies as $vacancy)
                        <div class="col-md-6 mt-3">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <a class="link-title"
                                            href="{{ route('vacancy.show', ['vacancy' => $vacancy->vacancy_id]) }}">
                                            <h5 class="card-title">
                                                {{ $vacancy->title }}
                                            </h5>
                                        </a>
                                        <h6>{{ date_format($vacancy->created_at, 'd M') }}</h6>
                                    </div>

                                    <div class="d-flex justify-content-between">
                                        <p class="card-text p-1">
                                            {{ strlen($vacancy->description) > 250 ? substr($vacancy->description, 0, 245) . '...' : $vacancy->description }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            @else
                <h6 class="ml-3 mt-3">Não há vagas</h6>
            @endif
        </section>

        <form method="POST" action="{{ route('vacancy.remove.candidates') }}">
            @csrf
            @method('DELETE')
            <div class="modal fade" id="removeCandidatesModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-scrollable" role="document">
                    @csrf
                    <div class="modal-content p-0">
                        <div class="modal-header">
                            <h5 class="modal-title">Removendo vagas candidatadas</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <h5>Vags</h5>
                            @foreach ($vacancies as $vacancy)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="vacancies_candidates[]"
                                        value="{{ $vacancy->id }}" id="check-remove{{ $vacancy->id }}">
                                    <label class="form-check-label" for="check-remove{{ $vacancy->id }}">
                                        {{ $vacancy->title }}
                                    </label>
                                </div>
                            @endforeach
                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-danger">Remover candidaturas</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection