routes/web.php
<?php

use App\Http\Controllers\CandidateController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\VacancyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::fallback(function () {
    return view('error404');
});

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');

Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register', [RegisterController::class, 'register'])->name('register.create');

Route::middleware('auth')->group(function () {

    Route::get('/', function () {
        return view('home.index');
    })->name('home');

    Route::resource('vacancy', VacancyController::class);

    Route::prefix('vacancy')->group(function () {
        Route::post('{vacancy}/add-candidates', [VacancyController::class, 'addCandidates'])->name('vacancy.candidates.add');
        Route::put('{vacancy}/paused', [VacancyController::class, 'alterPaused'])->name('vacancy.paused');
        Route::delete('remove/candidates', [VacancyController::class, 'removeCandidates'])->name('vacancy.remove.candidates');
    });

    Route::resource('candidate', CandidateController::class);

    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
});

resources/views/home/index.blade.php
@extends('layouts.template')

@section('title', 'Home')

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/home/style.css') }}">
@endsection

@section('content')
    <main class="content">

        <div class="area-logout">
            <h5>Olá {{Auth::user()->name}}</h5>
            <a href="{{route('logout')}}">Sair da conta</a>
        </div>

        <div class="content-main">
            <a href="{{ route('vacancy.index') }}">
                <div class="card">
                    <div class="card-body">
                        Área de vagas
                    </div>
                </div>
            </a>

            <a href="{{ route('candidate.index') }}">
                <div class="card">
                    <div class="card-body">
                        Área de candidatos
                    </div>
                </div>
            </a>
        </div>
    </main>
@endsection